version: '3.7'
services:
  rand_int:
    build: ./rand_int
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  rand_str:
    build: ./rand_str
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  service4:
    build: ./service4
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
  core_service:
    build: ./core_service
    ports:
    - target: 5007
      published: 5007
      protocol: tcp


